### ISSUE TITLE
Question regarding the OS

### ISSUE THREAD

**Issue by HoneyehYz** [RjDuan/AdvCam-Hide-Adv-with-Natural-Styles#10]
Hi, 
I tried installing and using your code on different operating systems, but each time get some issues with installing Cuda. I would appreciate it if you let me know what was the OS you were working on.

**Comment by RjDuan** [comment]
Thanks for your interest, the operating system is CentOS7 :)

Honeyeh ***@***.***> 于2021年6月18日周五 下午12:01写道：
