### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by HoneyehYz** [RjDuan/AdvCam-Hide-Adv-with-Natural-Styles#11]
Hi 
I am trying to run your project and I am getting the following error:
`ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory`
I already installed the libcudnn and I am not sure what is causing this issue. 
appreciate if you can help me fix that. 
Thanks

**Comment by RjDuan** [comment]
Hi,
Could you please check the version of your libcudnn?  Is it compatible with
your CUDA version?
You can try "nvidia-smi" to check the version of you CUDA .
Also, this link may help:
https://gist.github.com/Jongbhin/ad9aac8369751dbd84ca6a266a507bc7
 :)



Honeyeh ***@***.***> 于2021年8月22日周日 下午11:35写道：
