### ISSUE TITLE
About some experiment

### ISSUE THREAD

**Issue by jay1009** [RjDuan/AdvCam-Hide-Adv-with-Natural-Styles#7]
Hello, thanks for your code. I have some problem when I try it.
When I want to try the Pikachu.jpg in your data, I don't know how I transfer its style.
Should I set the Pikachu.jpg as content, and choose a style to transfer it?
Or set it as style, and set T-shirt as content?

I look forward to hearing from you.

**Comment by RjDuan** [comment]
Hi, thanks for your interest!
I tried several settings when performing the experiments:
1) Start from blank, set Pikachu as target style, but the resultant image
is confusing and messy.
2) Start from blank, set Pikachu as target content, better, but the face
details of Pikachu sort of lost.
3) Start from blank, set Pikachu as target content + style, further better,
the resultant image is as you see in the paper.
And the t-shirt (pasted with Pikachu) is captured in the physical
environment.
To be honest, I do think the Pikachu is an interesting case, but it is not
a good result regarding the proposed AdvCam.
As AdvCam using the style transfer technique as distance constraint, it
performs well on the stuff of unstructured details, e.g., stain, snow,
fire, etc.  but limited on structured details, e.g., line, face detail of
Pikachu.
Hope the information helps.

jay1009 ***@***.***> 于2021年6月7日周一 下午2:14写道：

**Comment by jay1009** [comment]
Thanks for your reply! It  really helps me a lot to try it.
