### ISSUE TITLE
About testing the image

### ISSUE THREAD

**Issue by jay1009** [RjDuan/AdvCam-Hide-Adv-with-Natural-Styles#8]
Hi, I have another problem.
Could I just call some function to test some result in your code?
I found there are many different versions about vgg19_test, and all of them couldn't work after I trying it.

I look forward to hearing from you.

**Comment by jay1009** [comment]
In machrisaa/tensorflow-vgg/test_vgg19.py, I can only reshape image into 224 x 224, but I think it may affect the results of the experiment.

**Comment by RjDuan** [comment]
Hi,
About VGG19 model, see /vgg19/vgg.py, it follows implementation by
machrisaa, but not exactly the same (normalization, input name etc. are
different), which may be the reason others do not work?
Regarding "reshape image into 224 x 224", you can wrap a reshape a function
as input transformation, then integrated it into the model (rewrite fprop
function in vgg.py), then you can feed input with any size.  AdvCam has a
similar setting, so it's ok to use input with other sizes, current it
outputs images with the size 400*400.

 And what do you mean about "call some function to test some result" ...?

Kind regards.

jay1009 ***@***.***> 于2021年6月8日周二 下午4:12写道：

**Comment by jay1009** [comment]
Thanks for your reply!!
"call some function to test some result" means that I guess there may be some code like machrisaa's test_vgg19.py, which is only used to test image's class and accuracy.
After I using machrisaa's test_vgg19.py, I always got the same class and similiar accuracy whatever I put in, as the following picture.
![bug](https://user-images.githubusercontent.com/28528806/121206258-e6f8e980-c8aa-11eb-9d9a-85097817d0cd.jpg)

Best regards.

**Comment by RjDuan** [comment]
No worries, many thanks for your feedback :)
If you refer to the code by machrisaa in test_vgg19.py
<https://github.com/machrisaa/tensorflow-vgg/blob/dcc2449a07201fb4ac99a98dc7bb95915322306c/test_vgg19.py>,

check the value of your input, make sure the value of your input images are
scaled to [0, 1].
They did this in function load_image().
<https://github.com/machrisaa/tensorflow-vgg/blob/dcc2449a07201fb4ac99a98dc7bb95915322306c/utils.py#L12>
(Note: if you use their test_vgg19.py, also use code vgg.py provided by
them, ours vgg.py are slightly different.)
Hope the information helps.

jay1009 ***@***.***> 于2021年6月8日周二 下午10:44写道：

**Comment by jay1009** [comment]
Thank you!!
I will try it as your suggestion.

Best regards.
